name: Packer Build Workflow

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "1.10.0"  # Packer version

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js Dependencies
        run: npm install
      - name: Run Integration Tests
        run: npm test

  build-ami:
    needs: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Create .env file with required values from GitHub Secrets
      - name: Create .env file
        run: |
          cat <<EOF > .env
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DIALECT=${{ secrets.DB_DIALECT }}
          NODE_ENV=${{ secrets.NODE_ENV }}
          EOF
        shell: bash

      - name: List .env file contents
        run: cat .env

      - name: Zip project artifact
        run: zip -r webapp-fork.zip .
        working-directory: .

      - name: List artifact contents
        run: ls -la webapp-fork.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup GCP Credentials
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run packer init
        working-directory: packer
        run: packer init machine-image.pkr.hcl

      - name: Run packer validate
        working-directory: packer
        run: packer validate machine-image.pkr.hcl

      - name: Build AMI with Packer
        working-directory: packer
        if: success()
        run: |
          packer build --force \
            -var "artifact_path=$(pwd)/../webapp-fork.zip" \
            -var "aws_region=us-east-2" \
            -var "aws_subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "ssh_username=ubuntu" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "db_user=${{ secrets.DB_USER }}" \
            machine-image.pkr.hcl
