name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.10.0"  # Adjust if needed

      - name: Check Packer Formatting
        run: |
          CHANGED=0
          # Find all .pkr.hcl files and compare formatted output to current file contents.
          for file in $(find . -type f -name "*.pkr.hcl"); do
            echo "Checking formatting for $file ..."
            FORMATTED=$(packer fmt -write=false "$file")
            ORIGINAL=$(cat "$file")
            if [ "$FORMATTED" != "$ORIGINAL" ]; then
              echo "ERROR: $file is not properly formatted."
              CHANGED=1
            else
              echo "$file is properly formatted."
            fi
          done
          if [ $CHANGED -ne 0 ]; then
            echo "One or more Packer templates are not formatted correctly. Please run 'packer fmt' locally to fix them."
            exit 1
          fi

      - name: Validate Packer Templates
        run: packer validate .
