name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.10.0"

      - name: Run Packer Init
        working-directory: packer
        run: packer init .

      - name: Check Packer Formatting Recursively
        working-directory: packer
        run: |
          # Run packer fmt recursively in "check" mode without writing changes.
          output=$(packer fmt -recursive -write=false .)
          if [ -n "$output" ]; then
            echo "Formatting issues detected in the following files:"
            echo "$output"
            exit 1
          else
            echo "All Packer templates are properly formatted."
          fi

      - name: Validate Packer Templates Recursively
        working-directory: packer
        run: |
          # Find and validate all .pkr.hcl files recursively.
          errors=0
          find . -type f -name "*.pkr.hcl" -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file"
            if ! packer validate "$file"; then
              errors=1
            fi
          done
          if [ $errors -ne 0 ]; then
            echo "One or more Packer templates failed validation."
            exit 1
          else
            echo "All Packer templates are valid."
          fi
